# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-29 15:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food_app', '0005_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('sub_total', models.IntegerField()),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food_app.Meal')),
                ('orders', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_details', to='food_app.Order')),
            ],
        ),
    ]
