# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-29 18:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food_app', '0006_orderdetails'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meal',
            old_name='short_decription',
            new_name='short_description',
        ),
    ]
