# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-31 18:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food_app', '0009_auto_20170731_1753'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderdetails',
            old_name='orders',
            new_name='order',
        ),
    ]
